const sampleData = {
  users: [
    {
      name: 'John Doe',
      email: 'admin@example.com',
      password: '123456',
      role: 'admin',
    },
    {
      name: 'Jane Doe',
      email: 'user@example.com',
      password: '123456',
      role: 'user',
    },
  ],
  products: [
    // Men's Fashion
    {
      name: 'Classic Ankara Print Shirt',
      slug: 'classic-ankara-print-shirt',
      category: "Men's Fashion",
      description: 'Traditional Nigerian Ankara fabric with modern fit',
      images: [
        '/images/sample-products/ankara-shirt-1.jpg',
        '/images/sample-products/ankara-shirt-2.jpg',
      ],
      price: 12500,
      brand: 'Native Pride',
      rating: 4.5,
      numReviews: 24,
      stock: 15,
      isFeatured: true,
      banner: '/images/banners/mens-fashion-banner.jpg',
    },
    {
      name: 'Designer Kaftan Agbada',
      slug: 'designer-kaftan-agbada',
      category: "Men's Fashion",
      description: 'Elegant embroidered kaftan for special occasions',
      images: [
        '/images/sample-products/agbada-1.webp',
        '/images/sample-products/agbada-2.webp',
      ],
      price: 45000,
      brand: 'Royal Attire',
      rating: 4.8,
      numReviews: 18,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Casual Linen Trousers',
      slug: 'casual-linen-trousers',
      category: "Men's Fashion",
      description: 'Comfortable linen trousers perfect for Nigerian weather',
      images: [
        '/images/sample-products/linen-trousers-1.jpg',
        '/images/sample-products/linen-trousers-2.jpg',
      ],
      price: 8500,
      brand: 'Comfort Wear',
      rating: 4.3,
      numReviews: 32,
      stock: 25,
      isFeatured: false,
      banner: null,
    },

    // Women's Fashion
    {
      name: 'Beautiful Gele and Iro Set',
      slug: 'beautiful-gele-iro-set',
      category: "Women's Fashion",
      description: 'Complete traditional attire with matching headgear',
      images: [
        '/images/sample-products/gele-iro-1.jpg',
        '/images/sample-products/gele-iro-2.jpg',
      ],
      price: 28000,
      brand: 'African Queen',
      rating: 4.7,
      numReviews: 42,
      stock: 12,
      isFeatured: true,
      banner: '/images/banners/womens-fashion-banner.webp',
    },
    {
      name: 'Designer Buba and Skirt',
      slug: 'designer-buba-skirt',
      category: "Women's Fashion",
      description: 'Handcrafted Nigerian traditional outfit',
      images: [
        '/images/sample-products/buba-skirt-1.webp',
        '/images/sample-products/buba-skirt-2.webp',
      ],
      price: 32000,
      brand: 'Yoruba Classic',
      rating: 4.9,
      numReviews: 28,
      stock: 6,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Modern Ankara Dress',
      slug: 'modern-ankara-dress',
      category: "Women's Fashion",
      description: 'Contemporary Ankara design for everyday wear',
      images: [
        '/images/sample-products/ankara-dress-1.webp',
        '/images/sample-products/ankara-dress-2.webp',
      ],
      price: 15000,
      brand: 'Afro Chic',
      rating: 4.4,
      numReviews: 56,
      stock: 20,
      isFeatured: false,
      banner: null,
    },

    // Electronics
    {
      name: 'Samsung Galaxy A54',
      slug: 'samsung-galaxy-a54',
      category: 'Electronics',
      description: 'Latest Samsung smartphone with excellent camera',
      images: [
        '/images/sample-products/galaxy-a54-1.jpg',
        '/images/sample-products/galaxy-a54-2.jpg',
      ],
      price: 245000,
      brand: 'Samsung',
      rating: 4.6,
      numReviews: 89,
      stock: 15,
      isFeatured: true,
      banner: '/images/banners/electronics-banner.webp',
    },
    {
      name: 'Infinix Hot 30i',
      slug: 'infinix-hot-30i',
      category: 'Electronics',
      description: 'Budget-friendly smartphone with great features',
      images: [
        '/images/sample-products/infinix-hot-1.jpg',
        '/images/sample-products/infinix-hot-2.jpg',
      ],
      price: 78000,
      brand: 'Infinix',
      rating: 4.2,
      numReviews: 124,
      stock: 35,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Tecno Spark 10',
      slug: 'tecno-spark-10',
      category: 'Electronics',
      description: 'Popular Tecno model with long battery life',
      images: [
        '/images/sample-products/tecno-spark-1.jpg',
        '/images/sample-products/tecno-spark-2.jpg',
      ],
      price: 92000,
      brand: 'Tecno',
      rating: 4.3,
      numReviews: 156,
      stock: 28,
      isFeatured: false,
      banner: null,
    },

    // Home Appliances
    {
      name: 'Scanfrost 55-inch Smart TV',
      slug: 'scanfrost-55-smart-tv',
      category: 'Home Appliances',
      description: 'Nigerian-made smart television with Android OS',
      images: [
        '/images/sample-products/scanfrost-tv-1.jpg',
        '/images/sample-products/scanfrost-tv-2.jpg',
      ],
      price: 285000,
      brand: 'Scanfrost',
      rating: 4.5,
      numReviews: 67,
      stock: 10,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Hisense 210L Refrigerator',
      slug: 'hisense-210l-refrigerator',
      category: 'Home Appliances',
      description: 'Energy-efficient refrigerator perfect for Nigerian homes',
      images: [
        '/images/sample-products/hisense-fridge-1.jpg',
        '/images/sample-products/hisense-fridge-2.jpg',
      ],
      price: 185000,
      brand: 'Hisense',
      rating: 4.4,
      numReviews: 45,
      stock: 8,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Binatone Blender with Grinder',
      slug: 'binatone-blender-grinder',
      category: 'Home Appliances',
      description: 'Powerful blender for Nigerian kitchen needs',
      images: [
        '/images/sample-products/binatone-blender-1.jpg',
        '/images/sample-products/binatone-blender-2.jpg',
      ],
      price: 25000,
      brand: 'Binatone',
      rating: 4.1,
      numReviews: 203,
      stock: 50,
      isFeatured: false,
      banner: null,
    },

    // Baby Products
    {
      name: 'Traditional Baby Christening Outfit',
      slug: 'traditional-baby-christening-outfit',
      category: 'Baby Products',
      description: 'Beautiful Nigerian traditional outfit for baby dedication',
      images: [
        '/images/sample-products/christening-outfit-1.webp',
        '/images/sample-products/christening-outfit-2.webp',
      ],
      price: 12000,
      brand: 'Little Angels',
      rating: 4.7,
      numReviews: 78,
      stock: 15,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Organic Baby Food Set',
      slug: 'organic-baby-food-set',
      category: 'Baby Products',
      description: 'Natural, organic baby food made with Nigerian ingredients',
      images: [
        '/images/sample-products/baby-food-1.jpg',
        '/images/sample-products/baby-food-2.jpg',
      ],
      price: 8500,
      brand: 'Pure Start',
      rating: 4.5,
      numReviews: 112,
      stock: 40,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default sampleData;
